require "colorize"

class Christmas

  def start
    create_tree
    christmas_greeting
  end

  def create_tree
  puts "                            |".colorize(:yellow)
  sleep(0.5)
  puts "                          \\ ' /".colorize(:yellow)
  sleep(0.5)
  print "                        -- ".colorize(:yellow)
  print "(*) ".colorize(:red)
  puts "--".colorize(:yellow)
  sleep(0.5)
  print "                           >".colorize(:green)
  print"*".colorize(:yellow)
  puts "<".colorize(:green)
  sleep(0.5)
  print "                          >0<".colorize(:green)
  print "@".colorize(:red)
  puts "<".colorize(:green)
  sleep(0.5)
  print "                         >>>".colorize(:green)
  print "@".colorize(:red)
  print "<<".colorize(:green)
  puts "*".colorize(:yellow)
  sleep(0.5)
  print "                        >".colorize(:green)
  print "@".colorize(:red)
  print ">".colorize(:green)
  print "*".colorize(:yellow)
  puts "<0<<<".colorize(:green)
  sleep(0.5)
  print "                       >".colorize(:green)
  print "*".colorize(:yellow)
  print ">>".colorize(:green)
  print "@".colorize(:red)
  print "<<<".colorize(:green)
  print "@".colorize(:red)
  puts "<<".colorize(:green)
  sleep(0.5)
  print "                      >".colorize(:green)
  print "@".colorize(:red)
  print ">>0<<<".colorize(:green)
  print "*".colorize(:yellow)
  print "<<".colorize(:green)
  print "@".colorize(:red)
  puts "<".colorize(:green)
  sleep(0.5)
  print "                     >".colorize(:green)
  print "*".colorize(:yellow)
  print ">>0<<".colorize(:green)
  print "@".colorize(:red)
  print "<<<".colorize(:green)
  print "@".colorize(:red)
  puts "<<<".colorize(:green)
  sleep(0.5)
  print "                    >".colorize(:green)
  print "@".colorize(:red)
  print ">>".colorize(:green)
  print "*".colorize(:yellow)
  print "<<".colorize(:green)
  print "@".colorize(:red)
  print "<>".colorize(:green)
  print "*".colorize(:yellow)
  print "<<0<".colorize(:green)
  print "*".colorize(:yellow)
  puts "<".colorize(:green)
  sleep(0.5)
  print "      \\".colorize(:red)
  print "*".colorize(:blue)
  print "/".colorize(:red)
  print "          >0>>".colorize(:green)
  print "*".colorize(:yellow)
  print "<<".colorize(:green)
  print "@".colorize(:red)
  print "<>0><<".colorize(:green)
  print "*".colorize(:yellow)
  print "<".colorize(:green)
  print "@".colorize(:red)
  puts "<<".colorize(:green)
  sleep(0.5)
  print "  ___\\".colorize(:red)
  print "\\".colorize(:red)
  print "U".colorize(:blue)
  print "//___".colorize(:red)
  print "     >".colorize(:green)
  print "*".colorize(:yellow)
  print ">>".colorize(:green)
  print "@".colorize(:red)
  print "><0<<".colorize(:green)
  print "*".colorize(:yellow)
  print ">>".colorize(:green)
  print "@".colorize(:red)
  print "><".colorize(:green)
  print "*".colorize(:yellow)
  puts "<0<<".colorize(:green)
  sleep(0.5)
  print "  |".colorize(:red)
  print "\\ ".colorize(:blue)
  print " | |".colorize(:red)
  print "  \\".colorize(:blue)
  print "|".colorize(:red)
  print "    >".colorize(:green)
  print "@".colorize(:red)
  print ">>0<".colorize(:green)
  print "*".colorize(:yellow)
  print "<0>>".colorize(:green)
  print "@".colorize(:red)
  print "<<0<<<".colorize(:green)
  print "*".colorize(:yellow)
  print "<".colorize(:green)
  print "@".colorize(:red)
  puts "<<".colorize(:green)
  sleep(0.5)
  print "  |".colorize(:red)
  print "  \\".colorize(:blue)
  print "| |".colorize(:red)
  print " _(".colorize(:green)
  print "UU".colorize(:red)
  print ")_".colorize(:green)
  print " >((".colorize(:blue)
  print "*".colorize(:magenta)
  print "))_".colorize(:blue)
  print ">0><".colorize(:green)
  print "*".colorize(:yellow)
  print "<0><".colorize(:green)
  print "@".colorize(:red)
  print "<<<0<".colorize(:green)
  print "*".colorize(:yellow)
  puts "<".colorize(:green)
  sleep(0.5)
  print "  |".colorize(:red)
  print "\\ \\".colorize(:blue)
  print "| |".colorize(:red)
  print "|".colorize(:green)
  print " / //".colorize(:red)
  print "|".colorize(:green)
  print "|".colorize(:blue)
  print ".*.*.*.".colorize(:magenta)
  print "|".colorize(:blue)
  print ">>>".colorize(:green)
  print "@".colorize(:red)
  print "<<".colorize(:green)
  print "*".colorize(:yellow)
  print "<<".colorize(:green)
  print "@".colorize(:red)
  puts ">><0<<<".colorize(:green)
  sleep(0.5)
  print "  |".colorize(:red)
  print "\\".colorize(:magenta)
  print "\\".colorize(:magenta)
  print "_|_|".colorize(:red)
  print "&&".colorize(:green)
  print "_//".colorize(:red)
  print " |".colorize(:red)
  print "|".colorize(:blue)
  print "*.*.*.*".colorize(:magenta)
  print "|".colorize(:blue)
  print "_".colorize(:red)
  print "\\".colorize(:blue)
  print "\\".colorize(:blue)
  print "db".colorize(:red)
  print "//".colorize(:blue)
  puts "_".colorize(:red)
  sleep(0.5)
  print "   \"\"\"\"".colorize(:green)
  print "|".colorize(:red)
  print "'.'.'.".colorize(:blue)
  print "|".colorize(:red)
  print "~".colorize(:green)
  print "|".colorize(:blue)
  print "*.*.*.*".colorize(:magenta)
  print "|".colorize(:blue)
  puts "   ____|_".colorize(:red)
  sleep(0.5)
  print "       |".colorize(:red)
  print "'.'.'.".colorize(:blue)
  print "|".colorize(:red)
  print "  ^^^^^^^".colorize(:magenta)
  print "|____|".colorize(:red)
  print ">>>>>>".colorize(:magenta)
  puts "|".colorize(:green)
  sleep(0.5)
  print "       ~~~~~~~~".colorize(:magenta)
  print "         '\"\"\"\"`".colorize(:red)
  print "------".colorize(:magenta)
  puts "'".colorize(:green)
  sleep(0.5)
  end

  def christmas_greeting
    puts "     __,_,_,___)          _______
    (--| | |             (--/    ),_)        ,_)
       | | |  _ ,_,_        |     |_ ,_ ' , _|_,_,_, _  ,
     __| | | (/_| | (_|     |     | ||  |/_)_| | | |(_|/_)___,
    (      |___,   ,__|     \\____)  |__,           |__,".colorize(:red)
  end

end
